apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  mongo-root-username: bWljcm9zZXJ2aWNlcw==   # base64("myuser")
  mongo-root-password: RDBuQ0BybWVsaTAxOTk0MA==   # base64("mypassword")